version: 2.1
jobs:
  prepare:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # - run:
      #     name: Install yarn
      #     command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Compute version number
          command: echo "0.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}" | tee version.txt
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - store_artifacts:
          path: yarn.lock
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # - run:
      #     name: Install Dependencies
      #     command: yarn install --immutable
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Build
          command: yarn build
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - hold:
          type: approval
          requires:
            - prepare
            - test
      - build:
          requires:
            - hold
